name: popper_mobile
description: Mobile App for Rem&Coil.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^4.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0

  shared_preferences: ^2.0.15
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  json_annotation: any

  dio: ^4.0.6
  retrofit: ^3.0.1+1
  jwt_decoder: ^2.0.1

  qr_code_scanner: ^1.0.0

  hive: ^2.2.2
  hive_flutter: ^1.1.0

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

  firebase_crashlytics: ^2.8.2
  firebase_core: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: any

  auto_route_generator: any
  injectable_generator: any
  json_serializable: any
  retrofit_generator: any
  hive_generator: any
  build_runner: any

  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: #ffffff
  image_path: "assets/icon/icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/