name: popper_mobile
description: Mobile App for Rem&Coil.

publish_to: 'none'

version: 0.2.2

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^6.4.0
  injectable: ^2.1.1
  get_it: ^7.4.0

  shared_preferences: ^2.1.0
  flutter_bloc: ^8.1.2
  json_annotation: ^4.8.1

  dio: ^5.1.1
  retrofit: ^4.0.1
  jwt_decoder: ^2.0.1

  mobile_scanner: ^3.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  intl: ^0.18.1
  cupertino_icons: ^1.0.5
  either_dart: ^0.4.0
  google_fonts: ^4.0.4
  timelines: ^0.1.0

  firebase_crashlytics: ^3.2.0
  firebase_core: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: any

  auto_route_generator: any
  injectable_generator: any
  json_serializable: any
  retrofit_generator: any
  hive_generator: any
  build_runner: any

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: #ffffff
  image_path: "assets/icon/icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/