name: popper_mobile
description: Mobile App for Rem&Coil.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^3.2.3
  injectable: ^1.2.1
  get_it: ^7.2.0

  shared_preferences: ^2.0.8
  dartz: ^0.10.0
  flutter_bloc: ^7.3.0

  dio: ^4.0.0
  retrofit: ^2.0.1
  jwt_decoder: ^2.0.1

  qr_code_scanner: ^0.6.1

  hive: ^2.0.5
  hive_flutter: ^1.1.0

  intl: ^0.17.0
  cupertino_icons: ^1.0.0
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^3.2.3
  retrofit_generator: any
  injectable_generator: any
  hive_generator: any
  build_runner: any
  json_serializable: any

  dart_code_metrics: ^4.9.1
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: #ffffff
  image_path: "assets/icon/icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/